apiVersion: apps/v1
metadata:
  name: nginx-daemonset
kind: DaemonSet
spec:
  selector:
    matchLabels:
      application: nginx
  template:
    metadata:
      labels:
        application: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.26

