apiVersion: batch/v1
metadata:
  name: example-job
kind: Job
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        application: nginx
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - echooo
            - "Hello world"
      restartPolicy: OnFailure
